@startuml
'https://plantuml.com/class-diagram


class Listener {
-  camundaService: CustomCamundaService
---
**@KafkaListener**
+ listen(dto: Dto)
}

class CustomCamundaService {
   - runtimeService: org.camunda.bpm.engine.RuntimeService
  ---
  +runProcess(dto: Dto): JobStatus \n\\\ runtimeService.startProcessInstanceByMessage(X)
}
Listener o- CustomCamundaService



@enduml