@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant OverdueContractProducer
queue topic
participant OverdueContractConsumer

OverdueContractProducer -> topic
topic -> OverdueContractConsumer

@enduml