@startuml
'https://plantuml.com/class-diagram

class Resume {
- uuid: String
- fullName: String
- contacts: HashMap<ContactType, Contact>
- sections: HashMap<SectionType, Section>
---
+ getUuid(): String
+ getFullName(): String
}


abstract class Section {
}

class SectionText {
    - text: String
}
class SectionList {
    - lists: List<String>
}




SectionText -> Section
SectionList --> Section

class Contact {
}


enum SectionType {
}
enum ContactType {
}
Resume *-- Contact
Resume *-- Section




@enduml