@startuml
'https://plantuml.com/activity-diagram-beta

start
:Получение счетов в ЕПД;
:Загрузка БВ в ЕПД;
:Разбор БВ в ЕПД;
:Создание П/П в ЕПД;
:Создание платежей в ЕПД;
:Определение счетов в ЕПД (куда бабки лить);
:Отправить платежи и счета в Arfix;
:Перекрытие в Arfix и уведомление в ЕПД;
:Перекрытие в ЕПД;
stop

@enduml
